permission = true
staging = true
ask_timeout = 30
ask_default = "deny"
snapshot = true

[rules]
"$HOME/.ssh/id_ed25519" = "ask"
"." = "allow"
".yolofs" = "hide"
"/bin" = "read"
"/etc" = "read"
"/lib" = "read"
"/lib64" = "read"
"/sbin" = "read"
"/usr" = "read"
"config.ini" = "ask"
"secret.txt" = "deny"
"yolofs.toml" = "hide"
