[mount]
ask_default = "deny"
ask_timeout = 30

[rules]
"/etc" = "allow-ro"
"/usr/bin" = "allow-rx"
"/usr/lib" = "allow-rx"
"/usr/share" = "allow-ro"
"/usr/bin/git" = "ask"
"$HOME/.bash_history" = "allow-rw"
# "." = "allow-rw"
